language: c
compiler:
- clang
- gcc

env:
  global:
  - PATH=~/.nimble/bin:$PATH

cache:
  directories:
  - ~/.choosenim
  - ~/.nimble

script:
- |
  if command -v choosenim; then
    choosenim -yes show
    choosenim -yes update stable
  else
    wget --quiet https://nim-lang.org/choosenim/init.sh && sh init.sh -y
  fi

after_script:
- ls --color ~/.nimble/bin
- choosenim
- nim
