language: c
compiler:
- clang
- gcc

env:
  global:
  - PATH=~/.nimble/bin:$PATH

cache:
  directories:
  - ~/.nimble

script:
- if command -v choosenim; then
    choosenim -y update stable ;
  else
    wget --quiet https://nim-lang.org/choosenim/init.sh && sh init.sh -y ;
  fi

after_script:
- ls --color ~/.nimble/bin
- choosenim
- nim
